# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf

# Prefix and send-prefix
unbind C-b
bind-key C-a send-prefix

# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Window navigation
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# Pane navigation
unbind C-h
unbind C-j
unbind C-k
unbind C-l
unbind h
unbind j
unbind k
unbind l

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Swap with adjacent pane using prefix + Shift-hjkl
bind -r H select-pane -L \; swap-pane -t !
bind -r J select-pane -D \; swap-pane -t !
bind -r K select-pane -U \; swap-pane -t !
bind -r L select-pane -R \; swap-pane -t !

# Resize panes with prefix + Ctrl-hjkl
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5
