# Core settings
set-option -g prefix C-a
set -g mouse on
set -g mode-keys vi
set -g status-keys vi

# Name the initial default numeric session
set-hook -g session-created "if -F '#{==:#{session_name},0}' \"rename-session \\\"work-session\\\"\""
