# Unbind old prefix and set a new one (c-a)
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.config/tmux/tmux.conf

# Enable mouse interactions
set -g mouse on
