# Unbind old prefix and set a new one (c-a)
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.config/tmux/tmux.conf

# Enable mouse interactions
set -g mouse on

bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

unbind C-h
unbind C-j
unbind C-k
unbind C-l

bind -r C-h select-pane -L
bind -r C-j select-pane -D
bind -r C-k select-pane -U
bind -r C-l select-pane -R
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Swap with adjacent pane using prefix + Shift-hjkl
bind -r H select-pane -L \; swap-pane -t !
bind -r J select-pane -D \; swap-pane -t !
bind -r K select-pane -U \; swap-pane -t !
bind -r L select-pane -R \; swap-pane -t !

# Resize panes with prefix + Ctrl-hjkl
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

